### ISSUE TITLE
2 dead wemos

### ISSUE THREAD

**Issue by peterkexas** [maragelis/ParadoxRs232toMqtt#18]
Hi I am trying to connect wemos d1 mini to Paradox sp 5500 alarm panel to serial and they burn.
What I am doing wrong?

**Comment by maragelis** [comment]
can you upload a picture with the connections

**Comment by peterkexas** [comment]
I am out right now but will see it tonight again with a multimeter.

**Comment by peterkexas** [comment]
Hello again!
I connect my wemos to my sp5500.
I have a mqtt server running on my rpi setup with node red on home assistant but when I try to arm , disarm nothing happened.
Eny help?
Wemos flashed with bin file that I download from here.
Thank you and sorry for my bad English!

**Comment by maragelis** [comment]
First check the mqtt topic that you are getting messages this can be done by either using node-red debug node or using an mqtt client. 
1) after flashing did you change the mqtt server ?
2) are you getting connect message in mqtt status topic.

**Comment by peterkexas** [comment]
I have change the mqtt server and my wifi credentials. I am trying to debug with node red but nothing happened. I was trying with paradox/# topic and nothing again. Sorry I am very new to this.

**Comment by maragelis** [comment]
Try #  or /#

**Comment by peterkexas** [comment]
I am trying to send you pm and i can not find it anyway.
With  /#  in Nodered I get massages from paradox/in but nothing from paradox/out.

**Comment by maragelis** [comment]
Try changing serial lines rxtx you might have them the wrong way

**Comment by mydakota** [comment]
Thanks I have tried that doesn't seem to make much difference. I am using a evo40 main board so when I get home I'll try my MG5050 see if it's the same I suspect it will be as ive herd others have used the Evo panels ok

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mydakota** [comment]
Omg sorry jumping on a Sim problem sorry thought you were talking to me lol

**Comment by peterkexas** [comment]
I double check them panel rx to d1 tx , panel tx to d1 rx and ground. On serial monitor I can see that connects to wifi but nothing for mqtt server, is that right?

**Comment by peterkexas** [comment]
I check debug from nodered i see only /paradox/in and when restart my wemos i have this : 

1/4/2019, 6:56:42 PMnode: 7cb71166.730df
/paradox/status : msg.payload : string[17]
"Paradox Connected"

1/4/2019, 6:56:44 PMnode: 7cb71166.730df
/paradox/status : msg.payload : string[23]
"ParadoxController V2.11"
I download mqtt.fx and i have the same messages
Have you any idea to help me?
thank you!

**Comment by maragelis** [comment]
thats correct you are working fine, are you not getting events on paradox/out ?

**Comment by peterkexas** [comment]
No!! nothing.

**Comment by peterkexas** [comment]
I have to flash blank.bin file first or flash it directly?

**Comment by maragelis** [comment]
yes flash blank.bin

**Comment by peterkexas** [comment]
nothing again flash v2 bin connects to my mqtt broker and wifi network but i dont have any message to /paradox/out

**Comment by maragelis** [comment]
my friend, v2 is at paradoxCTL/#

**Comment by peterkexas** [comment]
Sorry I am stupid.
But trying with paradoxCTL/# and pins 13 15 again nothing.
I am trying to copy your code for nodered and import to flow and has error so I can't importing it.

**Comment by peterkexas** [comment]
Thank you!!  thank you !!!
I have done it , managed to take messages from my panel on paradoxdCTL/out now another hard part to connect it with my home assistant via Nodered.
Thanks again for your help!!

**Comment by mydakota** [comment]
Good job ,
I'm interested on your node red useage to intergrate home assistant and how that works.
I've just changed some out put messages in code to remove all the " " symbols that home assistant has a hard time with example below

paradoxdCTL/out { armstatus:224, event:1, sub_event:1, dummy:Zone 01

This now works for arm disarm zone open closes restors and all the other out messages 
I just use a simple motion binary_sensor
In home assistant works a treat . But I'm still testing and need to verify this will not cause other issues

**Comment by peterkexas** [comment]
Thank you, if you can send me your code to test it on my setup.
You have to install nodered to machine runs home assistant and then install home assistant pallet and then connect them.
An example for this on how it works we have here paradox232tomqtt on wiki-pages hassio home assistant section

**Comment by mydakota** [comment]
Cool the main prob that home assistant had with these json message Hass didn't like more than two " " symbols anymore you have problems . Ive tryed templating to get things to work but ends up extramly complicated and unreliable. This way works very well and very simple solution .

**Comment by maragelis** [comment]
reading the hassio binary sensor https://www.home-assistant.io/components/binary_sensor.mqtt/ you could use:
 value_template: '{{ value.x }}'  

in the case of my project you would use 
value_template: '{{value_json.event}}'
payload_on: "1"
payload_off: "0"

**Comment by mydakota** [comment]
I personally had a hard time getting the template or value template to work with json but I'm  no HASS expert either. It will definitely be a good addition for this project to support Hass as it's got a large community. 

Slightly changing subject but I've been switching my comms between my MG5050 
and Evo 48 panel unfortunately I get no message from the Evo board I'm assuming it's got a different bit rate or something different I do know the Evo uses 24 digit headers dose that sound like it's not compatible have you talked to anyone with success with the EVO systems thanks.

**Comment by maragelis** [comment]
Evo has different message dynamic from 20 to (i dont know)

**Comment by mydakota** [comment]
Ah ok ;( my fav Paradox Panels are the Evos but hay with some exspanders and a couple of TM70 Keypads I'll still be happy with the MG5050 I guess. Thanks for the info

**Comment by maragelis** [comment]
I have created my own tm70 keypads using this project and openhab/habpanel looks good and works great, and also intergrated lights and heating . 
Just used cheap arduino tablets (60euros)

**Comment by peterkexas** [comment]
thanks you saved me!!!!

**Comment by maragelis** [comment]
Ok new release is up Hassio and updated test branch

**Comment by maragelis** [comment]
just to get the blood running 

![image](https://user-images.githubusercontent.com/12981331/50735225-03613b00-11b4-11e9-884e-5a3b1de45aa1.png)

**Comment by peterkexas** [comment]
Hi!!  Thanks very much ! V2 works like a charm.
Trying to figure out what is the command_topic to change the state !. The sensors work's fine for me but I can't arm or disarm from hass

**Comment by maragelis** [comment]
Check the wiki hassio v2 you will get your answer

**Comment by peterkexas** [comment]
:(  ?

**Comment by maragelis** [comment]
larm_control_panel:

platform: mqtt
state_topic: “paradoxdCTL/out/state”
payload_disarm: ‘{"password":“0000”,“Command”:“disarm”,“Subcommand”:"0"}’
payload_arm_night: ‘{"password":“0000”,“Command”:“sleep”,“Subcommand”:"0"}’
payload_arm_home: ‘{"password":“0000”,“Command”:“stay”,“Subcommand”:"0"}’
payload_arm_away: ‘{"password":“0000”,“Command”:“arm”,“Subcommand”:"0"}’

**Comment by peterkexas** [comment]
I saw that and add it to my configuration and I have state of my alarm but i can't arm or disarm the system.I must add command_topic to configuration to control the alarm.
Sorry for all that but I am trying to learn I have no idea about code and how works.
Thanks again!!

**Comment by mydakota** [comment]
Doesn't seem to matter what I do or what I try 
I can't arm disarm or any commands to panel via the paradoxdCTL/in .
I'm not sure what else to try mqtt messages definitely being sent just now response from alarm . Just brought the TM70 keypad and if I arm disarm via the keypad I get all armed states back via mqtt so frustrated lol

**Comment by mydakota** [comment]
Also don't you mean the command topic is
paradoxdCTL/in
Not paradoxCTL/in

**Comment by mydakota** [comment]
Yip receiving very well I can connect with IP150 via same port so it's got to be something related to the wemos. maybe I'll try change some user codes but I don't feel it's likely the issue as I can arm disarm via keypad ip150

**Comment by maragelis** [comment]
are you disconnecting the ip150 .
could you send all events recieved by mqtt when arming the system using the keypad . 
I want to see if you are recieving the event 48 sub 02 thats the software login event

**Comment by mydakota** [comment]
I definitely have ip150 disconnect when wemos on I'm fairly sure I'm getting those codes but give me a min I'll go arm trigger entry delay siren and disarm past you the output soon

**Comment by mydakota** [comment]
hasbian@hasbian-desktop:~$ mosquitto_sub -v -t '#'
paradoxdCTL/out { armstatus:224, event:2, sub_event:14, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:3, sub_event:2, dummy:}
paradoxdCTL/out { armstatus:224, event:2, sub_event:8, dummy:     Area 1     }
paradoxdCTL/status {"status":"Problem connecting to panel"}
paradoxdCTL/out { armstatus:224, event:2, sub_event:9, dummy:     Area 1     }
paradoxdCTL/out/state armed_away
paradoxdCTL/out { armstatus:224, event:2, sub_event:12, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:29, sub_event:2, dummy:     Area 1     }
paradoxdCTL/out/zone1 ON
paradoxdCTL/out { armstatus:224, event:1, sub_event:1, dummy:Zone 01         }
paradoxdCTL/out { armstatus:224, event:2, sub_event:13, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:2, sub_event:6, dummy:     Area 1     }
paradoxdCTL/out/state triggered
paradoxdCTL/out { armstatus:224, event:2, sub_event:4, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:36, sub_event:1, dummy:Zone 01         }
paradoxdCTL/out/state disarmed
paradoxdCTL/out { armstatus:224, event:2, sub_event:11, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:2, sub_event:7, dummy:     Area 1     }
paradoxdCTL/status {"status":"Problem connecting to panel"}
paradoxdCTL/out { armstatus:224, event:3, sub_event:3, dummy:}
paradoxdCTL/out { armstatus:224, event:38, sub_event:1, dummy:Zone 01         }
paradoxdCTL/out { armstatus:224, event:33, sub_event:2, dummy:Zone 01         }
paradoxdCTL/out { armstatus:224, event:32, sub_event:2, dummy:Zone 01         }
paradoxdCTL/out { armstatus:224, event:2, sub_event:8, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:2, sub_event:9, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:2, sub_event:8, dummy:     Area 1     }
paradoxdCTL/out { armstatus:224, event:2, sub_event:9, dummy:     Area 1     }

**Comment by mydakota** [comment]
paradoxCTL/in {"password":"1980","Command":"stay","Subcommand":"0"}
paradoxCTL/in {"password":"1980","Command":"arm","Subcommand":"0"}
paradoxdCTL/in {password:1234,Command:arm,Subcommand:0}
paradoxdCTL/in {password:1234,Command:arm,Subcommand:0}
paradoxCTL/in {"password":"1980","Command":"stay","Subcommand":"0"}
paradoxdCTL/in  {password:1980,Command:stay,Subcommand:0}

*WM: server
*WM: Adding parameter
*WM: port
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.107
*WM: Already connected. Bailing out.
*WM: IP Address:
*WM: 192.168.1.107
*WM: freeing allocated params!
Starting HTTP...
Starting SSDP...
returned command = 4
returned command = 4
returned command = 4
returned command = 4
returned command = 1

**Comment by maragelis** [comment]
ok try this topic 
paradoxdCTL/in 
 {"password":"1980","Command":"stay","Subcommand":"0"}

**Comment by maragelis** [comment]
paradoxCTL/in {"password":"1980","Command":"stay","Subcommand":"0"}
paradoxCTL/in {"password":"1980","Command":"arm","Subcommand":"0"}
paradoxdCTL/in {password:1234,Command:arm,Subcommand:0}  <-- Wrong Topic 
paradoxdCTL/in {password:1234,Command:arm,Subcommand:0} <-- not strings
paradoxCTL/in {"password":"1980","Command":"stay","Subcommand":"0"} <-- Wrong Topic 
paradoxdCTL/in {password:1980,Command:stay,Subcommand:0} <-- Not strings 
paradoxdCTL/in {"password":"1980","Command":"stay","Subcommand":"0"} <-- CORRECT

**Comment by mydakota** [comment]
pub=
`hasbian@hasbian-desktop:~$ mosquitto_pub -h 192.168.1.100 -t paradoxdCTL/in -m "{"password":"1980","Command":"arm","Subcommand":"0"}"`

sub =
`paradoxdCTL/in {password:1980,Command:arm,Subcommand:0}
`
serial mon=
`returned command = 4
`

**Comment by maragelis** [comment]
the only thing we can do is to set trace to 1 and get more debug messages

**Comment by maragelis** [comment]
i see the problem just wait a min will get back soon

**Comment by mydakota** [comment]
Cool I have to go sleep lol 12pm here now got cameras to install in morning need some rest lol. Thanks for your help much appreciated and if you find issue post I'll see in morning and have a go thanks again. Also keen to try trace set to 1 I'm picking that's in Arduino code b4 uploading or can I command from serial interface .....

**Comment by maragelis** [comment]
try new  realese 20190111

**Comment by maragelis** [comment]
https://github.com/maragelis/ParadoxRs232toMqtt/releases/tag/20190114a

**Comment by maragelis** [comment]
https://github.com/maragelis/ParadoxRs232toMqtt/releases/tag/20190125

**Comment by peterkexas** [comment]
Καλησπέρα Πάνο!!
![image](https://user-images.githubusercontent.com/28904794/52167639-d8242a00-2726-11e9-9f1a-9ed34a171738.png)
I have no idea what to do with that!
Can you help me?

**Comment by tasosstr** [comment]
Καλησπέρα, έχεις συνδέσει τον πίνακα με το  D7 , D8 ?

**Comment by peterkexas** [comment]
Ναι

**Comment by tasosstr** [comment]
![paradox connection](https://user-images.githubusercontent.com/20454403/52169121-0b24e880-273c-11e9-88a9-1f3ba1e00d24.jpg)

Σύνδεση σε SP7000 το ίδιο είναι και για SP6000, SP5500

**Comment by tasosstr** [comment]
Είχα το ίδιο πρόβλημα και τελικά ήταν αλλαγή στην Serial port φαντάζομαι χρησιμοποιής την τελευταία έκδοση https://github.com/maragelis/ParadoxRs232toMqtt/

Έχεις βάλει την IP και την πόρτα για το MQTT Server ?

**Comment by tasosstr** [comment]
![paradox connection final connection](https://user-images.githubusercontent.com/20454403/52169273-285ab680-273e-11e9-928a-b317079dc74c.jpg)

Αυτή είναι η τελική σύνδεση πάνω στον πίνακα, με το converter τάσης απο >12V σε 5V για τον controller

**Comment by peterkexas** [comment]
Έχω συνδέσει σωστά περνώ σήματα από τον πίνακα στον mqtt. Όταν προσπαθώ να του στείλω arm_away η απάντηση που έχω είναι αυτό τις φωτογραφίας παραπάνω.

**Comment by tasosstr** [comment]
Νομίζω στέλνεις λάθος command:

paradoxdCTL/out/state gives values:

disarmed
armed_home
armed_away
triggered

--------------------

Τα command που στέλνουμε είναι 

json Command payload template
{ "password":"1234", "Command":"arm", "Subcommand":"0" }

password is user 4 digit password

Command can be one of the following

arm,
disarm,
sleep,
stay,
bypass,
armstate,
zonestate,
panelstatus

subcomand depends on command ,

if Command is arm,sleep,disarm subcomand is partition

if Command is bypass subcomand is zone number from 0 to 31

if Command is panelstatus subcomand 0 = panel data
or subcomand 1 = panel voltage and battery data 


'Αρα δοκίμασε να στείλεις 
{ "password":"1234", "Command":"arm", "Subcommand":"0" }

όπου 1234 θα βάλεις τον κωδικό σου που οπλίζεις - αφοπλίζεις τον συναγερμό σου.

**Comment by peterkexas** [comment]
Το command το στέλνω από mqtt alarm control panel home assistant και το payload_arm_away: '{ "password":"1234", "Command":"arm", "Subcommand":"0" }' με password τον δικό μου τετραψήφιο.

**Comment by peterkexas** [comment]
Έχω κάνει ότι ακριβώς περιγράφει ο Παναγιώτης αλλά εξακολουθώ να μην μπορώ να οπλισω η να αφοπλίσω τον συναγερμό. Απλά είδα στο mqtt.fx ότι δεν κάνει connect with panel όταν προσπαθώ να οπλισω από Home assistant.

**Comment by peterkexas** [comment]
Θα το δοκιμάσω έτσι και θα ενημερώσω. Ευχαριστώ πολύ για την βοήθεια.

**Comment by tasosstr** [comment]
Μακάρι να μπορούσα να βοηθήσω περισσότερο ...
Νά σαι καλά.
Καλή τύχη σου εύχομαι :-)

**Comment by peterkexas** [comment]
Καλημέρα! @tasosstr δοκίμασα να στείλω απο mqtt.fx αλλα δεν κάνει τιποτα παλι αρα δεν ειναι απο το home assistant

**Comment by maragelis** [comment]
Φίλε Πανό δες λίγο της συνδέσεις και το user, δοκίμασε και άλλο esp8266 μήπως έχεις κάψει την έξοδο

**Comment by tasosstr** [comment]
Καλημέρα και από εμένα, δοκίμασε Trace=1 στο MQTT και κοιτα στο serial monitor τι πακέτα στέλνει ... μήπως έχεις reboot ...

**Comment by maragelis** [comment]
Αν το έχεις με το arduino IDE κάνε set to swapserial σε 0 και κάνε της συνδέσεις στο rx/tx στο eap8266

**Comment by peterkexas** [comment]
Exώ κάνει flash σε κενό esp8266 με 20190130  ParadoxAlarmSystemOTA.bin με ESPEasy flasher έχω συνδέσει RX D7 και TX D8 και πέρνω κανονικά τα events στον MQTT. To μόνο που δεν κάνει είναι όπλιση και αφόπλιση.

**Comment by peterkexas** [comment]
sorry TX D7 και RX D8

**Comment by tasosstr** [comment]
Όταν λες event λες κάτι τέτοιο

![event](https://user-images.githubusercontent.com/20454403/52177232-8cc15880-27c6-11e9-8c49-c9c00f594e22.jpg)

Τι μοντέλο πίνακα χρησιμοποιείς ?

**Comment by peterkexas** [comment]
ναι
![image](https://user-images.githubusercontent.com/28904794/52177263-ed509580-27c6-11e9-8f89-b41be2fc50f3.png)

**Comment by peterkexas** [comment]
paradox sp5500

**Comment by tasosstr** [comment]
Κακό αυτο :-(

Βρες 
#define Serial_Swap 1 //if 1 uses d13 d15 for rx/tx 0 uses default rx/tx

και άλλαξε το με 

#define Serial_Swap 0 //if 1 uses d13 d15 for rx/tx 0 uses default rx/tx

Κάνε Build - upload (έτσι τα Rx Tx απο τον ESP θα πάνε αντίστοιχα στον πίνακα αντί για το D7 και D8, να ξέρεις όμως ότι άν χρειαστεί να ξαναπρογραμματίσεις τον ESP θα πρέπει να αποσυνδέσεις τα καλώδια από Rx Tx  για να μήν έχεις error message)

Και ξαναδοκίμασε (έτσι θα δούμε αν έχει καεί κάποιο pin.

Δεν πιστεύω να χρησιμοποιείς καμία αντίσταση, αν ναι βγάλτην

**Comment by tasosstr** [comment]
Να σαι καλά ... Μακάρι να το πετύχεις ! ! !

Εφόσον και ετσι δεν δουλευει τοτε γυρνα το πάλι 

#define Serial_Swap 1 //if 1 uses d13 d15 for rx/tx 0 uses default rx/tx

Μην ξεχάσεις να βγάλεις τα καλώδια απο το Rx Tx πριν το Upload αφου τελειώσει τότε βάλτα ξανά, και άνοιξε το Serial Monitor 9600 Baud rate .

Στο MQTT γράψε στο Publish 
Trace=1
Αυτό θα ενεργοποιήση το debug mode 
Δοκίμασε πάλι να κάνεις arm ή stay ή sleep 
και κάνε paste ότι βγάλει το serial monitor (χώρις τον κωδικό σου αν τον εμφανίσει πουθενά)

**Comment by maragelis** [comment]
Φίλε Πανό και Τάσο το debug είναι στο D4 Tx1 θα χρειαστείς usb uart

**Comment by tasosstr** [comment]
Εχείς δίκιο φιλε μου,

Αφού το συνδέσεις (με baud rate 9600) θα αρχίσεις να παίρνεις τιμές σαν τα παρακάτω ...

d*ύ¶Hlxν–ΡCIΈKRKxωΩΑHΫ�>π�Ο$ιώώstate: 5 -> 0 (0)
rm 0
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 9
cnt 

connected with Vodafone_2.4G-03971, channel 1
dhcp client start...
ip:192.168.1.8,mask:255.255.0.0,gw:192.168.1.1
Starting HTTP...
Starting SSDP...
pm open,type:2 0
Trace is ON

**Comment by peterkexas** [comment]
Καλημέρα σε όλους . Δυστυχώς δεν έχω usb uart για να δοκιμάσω. Αν δεν υπάρχει άλλος τρόπος να κάνω debug να περιμένω ίσως κάποιο νέο release από τον φίλο μας Παναγιώτη που φυσικά τον ευχαριστούμε πολύ για την δουλειά που έχει κάνει.

**Comment by maragelis** [comment]
Φοβαμαι μην εχεις καψει την RX επανω στο paradox.

**Comment by peterkexas** [comment]
Όχι δεν έχει κάτι τέτοιο γιατί αν βάλω το ip100 που έχω δουλεύει κανονικά

**Comment by peterkexas** [comment]
Έχει να κάνει τίποτα από προγραμματισμό τις μονάδος η καμία σχέση?

**Comment by maragelis** [comment]
Φιλε Πανο, μια βοηθεια please. Να κανεις flash το ParadoxAlarmSystemOTA.ino.d1_mini.bin που ειναι εδω https://github.com/maragelis/ParadoxRs232toMqtt/tree/Dev/ParadoxAlarmSystem/ParadoxAlarmSystemOTA

enable trace, send TRACE=1 στο mqtt,
send arm,
Να μου κανεις paste ολα τα μηνύματα απο το paradoxCTL/status

**Comment by peterkexas** [comment]
Δεν με κουράζεις καθόλου ίσα ίσα που με βοηθάτε και ευχαριστώ!!!
Το απόγευμα που θα φτάσω σπίτι θα το κάνω και θα ενημερώσω.

**Comment by peterkexas** [comment]
Δεν ξέρω αν τα εχω κάνει σωστά αλλά
![screenshot 2019-02-04 17 33 54](https://user-images.githubusercontent.com/28904794/52218493-73420e80-28a3-11e9-993d-8ef8d0b6b788.png)

![screenshot 2019-02-04 17 32 16](https://user-images.githubusercontent.com/28904794/52218501-7937ef80-28a3-11e9-9551-ebf7024064c0.png)

Το log apo to MQTT.fx

> 2019-02-04

 17:31:22,199  INFO --- MqttFX ClientModel             : sucessfully published message Trace=1 to topic Trace=1 (QoS 0, Retained: false)
2019-02-04 17:31:40,838  INFO --- PublishController              : publish
2019-02-04 17:31:42,105  INFO --- PublishController              : publish
2019-02-04 17:31:42,304  INFO --- PublishController              : publish
2019-02-04 17:32:02,127  INFO --- PublishController              : publish
2019-02-04 17:32:02,129  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-04 17:32:02,130  INFO --- MqttFX ClientModel             : sucessfully published message { "password":"****", "Command":"arm", "Subcommand":"0"} to topic paradoxdCTL/in (QoS 0, Retained: false)
2019-02-04 17:32:02,413  INFO --- MqttFX ClientModel             : messageArrived() with topic: paradoxdCTL/status
2019-02-04 17:32:02,414  INFO --- MqttFX ClientModel             : messageArrived() added: message #29 to topic 'paradoxdCTL/status'
2019-02-04 17:33:28,390  INFO --- PublishController              : publish
2019-02-04 17:33:28,392  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-04 17:33:28,392  INFO --- MqttFX ClientModel             : sucessfully published message { "password":"****", "Command":"arm", "Subcommand":"0" } to topic paradoxdCTL/in (QoS 0, Retained: false)
2019-02-04 17:33:28,578  INFO --- MqttFX ClientModel             : messageArrived() with topic: paradoxdCTL/status
2019-02-04 17:33:28,579  INFO --- MqttFX ClientModel             : messageArrived() added: message #30 to topic 'paradoxdCTL/status'
2019-02-04 17:38:12,201  INFO --- PublishController              : publish 
2019-02-04 17:38:12,203  INFO --- MqttFX ClientModel             : attempt to add PublishTopic
2019-02-04 17:38:12,204  INFO --- MqttFX ClientModel             : sucessfully published message  to topic Trace=0 (QoS 0, Retained: false)
2019-02-04 17:38:14,132  INFO --- PublishController              : publish

>

**Comment by maragelis** [comment]
Το μήνυμα 28 τι λέει μπορείς να μου τα στείλεις όλα. Μου δείχνεις μόνο το 6 και 29

**Comment by tasosstr** [comment]
Καλησπέρα και από εμένα, τώρα επέστρεψα και είδα ¨κινηση"

Επειδή έχω ένα WEMOS για άλλον αυτοματισμό, το δοκίμασα παράλληλα σε δευτερή πλακέτα που έχω στον πάγκο SP7000.

Υποψιν (επειδή και εγώ την πάτησα, μου τραβηχτηκε από λάθος το gnd και εστειλα αδιαβαστο το Wemos :-(  )  Πρώτα σύνδεση Gnd Wemos --Gnd Paradox

![d7 d8](https://user-images.githubusercontent.com/20454403/52223425-447d6580-28ae-11e9-8a54-2adf157c0080.jpg)
![send panelstatus 2nd wemos](https://user-images.githubusercontent.com/20454403/52223432-46dfbf80-28ae-11e9-83e2-131c213a5e58.jpg)

το command paradoxdCTL/in1 είναι compile απο μένα για το δεύτερο Controller

![send panelstatus 2nd wemos](https://user-images.githubusercontent.com/20454403/52223745-fb79e100-28ae-11e9-817f-af8b56f4f80f.jpg)


Εγώ φοβάμαι μήπως έχει καεί το Τχ απο το Wemos

**Comment by peterkexas** [comment]
Όλα τα παραπάνω εκτός απο το 9 λένε {"status":"Problem connecting to panel"}

**Comment by maragelis** [comment]
Τάσος έχεις κάποιο πρόβλημα με wemos

**Comment by tasosstr** [comment]
Οχι φίλε μου 

Έκαψα απο λάθος ενα NodeMCu μου έφυγε η γείωση ενώ λειτουργούσε :-(

**Comment by tasosstr** [comment]
'Εβαλα την φωτογραφία με το Wemos για να δεί την συνδεσμολογία μήπως τα έχει συνδέσει λάθος,
γιατί το Paradox connected είναι μήνυμα απο το MQTT και όχι απο το login στο paradox, είναι πολύ πιθανό λοιπόν να έχει συνδέσει λάθος τα Tx Rx

**Comment by peterkexas** [comment]
πατησα το reset και στον mqtt εχω¨
1. {"status":"Paradox Disconnected"}
2. {"status":"Paradox connected"}
3. {"status":"Problem connecting to panel"}
και οταν κανω publish
{ "password":"2607", "Command":"arm", "Subcommand":"0"}
εχω
{"status":"Problem connecting to panel"}

**Comment by peterkexas** [comment]
αν ηταν ανάποδα θα είχα τα events απο τις ζώνες 
![screenshot 2019-02-04 19 15 33](https://user-images.githubusercontent.com/28904794/52224686-4694f380-28b1-11e9-9a9b-0adf3fa77a34.png)

**Comment by maragelis** [comment]
Φίλε Πανό στείλε ένα TRACE=1 και μετά την εντολή με το arm.

**Comment by maragelis** [comment]
Πριν το λάθος πρέπει να σου βγάλει ένα ακόμα μήνυμα

**Comment by maragelis** [comment]
Ναι ρε Τάσο φίλε Πανό sorry Trace=1

**Comment by maragelis** [comment]
Μήπως έχετε google hangouts να μπορούμε να κάνουμε πιο άμεσο chat

**Comment by peterkexas** [comment]
Φίλε Τάσο δεν εχεις δικιο δοκίμασα να τα βάλω ανάποδα στον Μqtt μου έβγαλε άμεσα  {"status":"Paradox Disconnected"} και τίποτα αλλο,
όταν τα επανέφερα κανονικά  {"status":"Paradox connected"}  και   {"status":"Problem connecting to panel"}

**Comment by tasosstr** [comment]
![mqtt no rxtx connected](https://user-images.githubusercontent.com/20454403/52226319-4a2a7980-28b5-11e9-8558-14d91079e84d.jpg)

Και φυσικά και έχω δίκιο κοιτα παραπάνω , αποσύνδεσε το Rx και το Tx και δοκίμασε πάλι

**Comment by tasosstr** [comment]
Στο παραπάνω γράφει Paradox connected αλλά δεν υπάρχει σύνδεση με τον πίνακα ...

**Comment by tasosstr** [comment]
Φίλε ποτε άλλαξες τελευταία φορά μπαταρία ?

**Comment by tasosstr** [comment]
Στον πίνακα ... υπάρχει μια πιθανότητα αν η μπαταρία είναι πάνω απο 3 χρόνια και έχει φουσκώσει να κάνει παλαβα .... δοκίμασε να βγάλεις τον θετικό πόλο και ξαναδοκίμασε...

**Comment by tasosstr** [comment]
Πως τροφοδοτείς το Wemos? Μπορείς να μας στείλεις μία φωτογραφία με την συνδεσμολογία σου ?

**Comment by peterkexas** [comment]
Δεν είναι η μπαταρία εμπιστεύσου με!!!Εχεις δικιο για  {"status":"Paradox Disconnected"}
{"status":"Paradox connected"} αλλα οταν ειναι συνδεδεμενο βγαζει και  {"status":"Problem connecting to panel"}.

τροφoδοσια δινω απο πλακετακι 12v σε 5v USB ->micro USB->wemosD1

**Comment by tasosstr** [comment]
Μπορείς να το δοκιμάσεις με τροφοδοσία από το usb του PC και Gnd απο το Wemos Σε Gnd στον πίνακα ?

**Comment by maragelis** [comment]
@peterkexas  το εμαιλ σου να σε βαλω σε chat

**Comment by peterkexas** [comment]
Ναι pkexagiopoulos@gmail.com
Θα φύγω για λίγο και θα ξανάρθω

**Comment by maragelis** [comment]
Issue solved, thanks to @peterkexas  and @tasosstr  for you help.
New realease v2.1.1

**Comment by peterkexas** [comment]
Paradox SP5500 @peterkexas  (Working control from Home assistant and live events)
