### ISSUE TITLE
OTA

### ISSUE THREAD

**Issue by mydakota** [maragelis/ParadoxRs232toMqtt#19]
Hi guys,
I’ve uploaded my code and changed setup wifi and MQTT address I can see the device on my network ip 192.168.1.9 now if I try browsing to that address it fails to connect.
Is this normal as I was thinking it should log me into the same setup page after first flashing it . Maybe my arduino library’s are out of date not sure .

**Comment by mydakota** [comment]
{"mqtt_server":"192.168.2.230","mqtt_port":"1883"}*WM: Adding parameter
*WM: server
*WM: Adding parameter
*WM: port
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.98
*WM: Already connected. Bailing out.
*WM: IP Address:
*WM: 192.168.1.98

**Comment by mydakota** [comment]
Also I noticed the matter is hasn't changed from 192.168.2.230 to my 192.168.197 server.
I've tried changing it in code then uploading it but it won't change I can't access web page to change it either seems very weird please help

**Comment by mydakota** [comment]
```

⸮Dp⸮tAhlE⸮⸮CXH⸮⸮{"mqtt_server":"192.168.1.197","mqtt_port":"1883"}*WM: Adding parameter
*WM: server
*WM: Adding parameter
```
*WM: port
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.98
*WM: Already connected. Bailing out.
*WM: IP Address:
*WM: 192.168.1.98
```

blanked the flash of d1min and reloaded and config properly but this is my output via serial mon.
d1 mini is connected to paradox serial port as well rx and tx are correctly reversed.

**Comment by maragelis** [comment]
Use arduino core 2.3.0 and you should be ok. Had those issues with 2.4

**Comment by mydakota** [comment]
Hi thanks for reply ,
I'm a bit new to Arduino so to change the Arduino core to 2.3.0 do I do that I the library update section . Sorry to ask such a noobish question.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SauRoNZA** [comment]
> Use arduino core 2.3.0 and you should be ok. Had those issues with 2.4

Does that fix the problem with not having access to the web interface once it's connected to Wifi? Or is that the standard behaviour?

**Comment by maragelis** [comment]
There is no web interface

**Comment by mydakota** [comment]
Ok I've change core files still the same but sounds like from what maragelis says theres no web interface . And the only work around to fix the incorrect mqtt Ip address was to reflash the esp with a blank.bin otherwise it would just rember the old changes . So far I've had no indication of comms between my paradox board and esp but ATM I'm running with out a keypad so maybe a issue . I'll have to wait untill I can pick up a keypad for testing . Thanks for all the help and getting me on the correct core files big help ....

**Comment by maragelis** [comment]
just turn off you wifi router the AP will come up and you can change the mqtt server

**Comment by mydakota** [comment]
Omg brilliant that thanks lol
