### ISSUE TITLE
MQTT authentication

### ISSUE THREAD

**Issue by ciscozine** [maragelis/ParadoxRs232toMqtt#25]
Hi, 
Does the project have authentication MQTT support?
thanks

**Comment by maragelis** [comment]
Change this line from
if (client.connect(charBuf,root_topicStatus,0,false,"Paradox Disconnected")) {
to
if (client.connect(charBuf, username, password, root_topicStatus,0,false,"Paradox Disconnected")) {

**Comment by maragelis** [comment]
look at this 
https://github.com/knolleary/pubsubclient/issues/462

**Comment by ciscozine** [comment]
Thanks!
