### ISSUE TITLE
ESP8266 and voltage regulator schema connection on MG5050

### ISSUE THREAD

**Issue by colcm** [maragelis/ParadoxRs232toMqtt#38]
Hello,

I have one ESP8266 and one Voltage regulator (3V and 5V from 12V  - YwRobot 545043).
Can you help me with a schema how to connect all these components to a Paradox MG5050 panel, please?

Thank you!

**Comment by maragelis** [comment]
the YwRobot 545043 is a bread board regulator it cannot be used easily. Get yourself a good buck converter something like this. 
https://www.ebay.com/itm/Adjustable-DC-DC-Buck-Step-down-Converter-5V-24V-To-3-3V-9V-12V-3A-Power-Supply-/122078008388

**Comment by colcm** [comment]
Hello,

and how can I use the 12V and GND from MG5050 in this combination (ESP8266 and convertor)? Can I use the GND from MG5050 to be common for ESP8266 and convertor?

Thank you!

**Comment by maragelis** [comment]
![image](https://user-images.githubusercontent.com/12981331/52876366-b6339a00-315f-11e9-93ef-690577cf2ecf.png)
