### ISSUE TITLE
commands

### ISSUE THREAD

**Issue by chrisgsauto** [maragelis/ParadoxRs232toMqtt#41]
Hi Panagiotis,
Congratulations for your amazing job. i tested this with SP5500 and works perfectly with hassio.
But the commands "zonestate", "armstate" have no response. Everything else (arm, disarm, etc) working perfect. Any opinion??? 
Thanks in advance,
Christos

**Comment by maragelis** [comment]
@Chrisgsauto are you using the master branch ? If yes, keep in mind those actions are sent to the /status topic. Also just to keep you updated on the next version zonestate will be removed, it will be combined into panelstatus command.
