### ISSUE TITLE
libs

### ISSUE THREAD

**Issue by au190** [maragelis/ParadoxRs232toMqtt#51]
Thanks for the great program !

Is tha possibile to uplod the correct libraries what you are using to compile this code ?

Thx Robert.

**Comment by Egyras** [comment]
you get get all from GIT:

Libraries:
Arduino core 2.4.1
WifiManager by tzapu 0.12.0
PubSubClient by Nick O`Leary 2.6.0

**Comment by au190** [comment]
Thx
Its a great work!
