### ISSUE TITLE
Wiki: RX TX order

### ISSUE THREAD

**Issue by dlaszlo** [maragelis/ParadoxRs232toMqtt#54]
In the wiki on the figure (Paradox Side), the RX TX PIN order is wrong:

https://user-images.githubusercontent.com/12981331/52876366-b6339a00-315f-11e9-93ef-690577cf2ecf.png

 The right order is (from top to bottom): TX RX GND VCC

**Comment by maragelis** [comment]
Thanks for that @dlaszlo will fix asap.

**Comment by dlaszlo** [comment]
Thank you.
