### ISSUE TITLE
Analyzing the Data 

### ISSUE THREAD

**Issue by augisbud** [maragelis/ParadoxRs232toMqtt#6]
Hello, I got mine Paradox MG5050 running and I can arm/disarm it using mqtt json, however I am not receiving the armstatus, this is my json message
{ "armstatus":224, "event":2, "sub_event":9, "dummy":"     Area 1     "}

**Comment by augisbud** [comment]
I have seen that you're using openhab2, could you provide me your .items file? and everything else you use

**Comment by maragelis** [comment]
you should be getting a event:06 sub_event:05 to 04 thats the arm event

**Comment by maragelis** [comment]
I use node-red to filter the events and send the messages i want  to openhab

**Comment by maragelis** [comment]
Can i close the issue
