### ISSUE TITLE
Is there a way to use Arduino UNO with ethernet?

### ISSUE THREAD

**Issue by pilievwm** [maragelis/ParadoxRs232toMqtt#62]
Hi Maragelis,

One question is repeating in my mind for months.
Is there an easy way to use Arduino ethernet-based module instead WIFI?
Sometimes WIFI is weak.

Regards
Peter

**Comment by maragelis** [comment]
yes you can, its quite easy I would say. You would have to swap out the comunication from wifi to Ethernet. (remove the esp libs)
