### ISSUE TITLE
Inject panic event e.g. fire, medical?

### ISSUE THREAD

**Issue by mharizanov** [maragelis/ParadoxRs232toMqtt#70]
I am interested in implementing a software panic button.
Typically I would need to press 1+3 to on the keyboard to activate panic mode, can that be achieved by injecting a command?
Thanks :)

**Comment by maragelis** [comment]
According to the api no you cannot. What you can do is add a duress user, which when armed or disarmed will send a duress signal(help wanted) to your alarm provider.

**Comment by mharizanov** [comment]
OK, thanks for the tip.
